name: campo_harmonico
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+3

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter




  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  splashscreen: ^1.3.5
  flutter_spinkit: ^4.1.2
  bottom_navy_bar: ^5.5.0
  dots_indicator: ^1.2.0
  firebase_admob: ^0.9.3+4
  page_indicator: ^0.4.1


dev_dependencies:

  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - images/A#.png
    - images/A.png
    - images/C#.png
    - images/C.png
    - images/D#.png
    - images/D.png
    - images/E.png
    - images/F#.png
    - images/F.png
    - images/G#.png
    - images/G.png
    - images/logodef.png
    - images/logo.png
    - images/cAm.png
    - images/cAmd.png
    - images/cBmd.png
    - images/cC.png
    - images/cCm.png
    - images/cCmd.png
    - images/cD.png
    - images/cDm.png
    - images/cDmd.png
    - images/cE.png
    - images/cEm.png
    - images/cEmd.png
    - images/cF#.png
    - images/cF#m.png
    - images/cF.png
    - images/cF#md.png
    - images/cG#.png
    - images/cG.png
    - images/cGmd.png
    - images/cBm.png
    - images/cA.png
    - images/cC#m.png
    - images/cG#m.png
    - images/cB.png
    - images/B.png
    - images/cD#m.png
    - images/cGm.png
    - images/cBb.png
    - images/cC#.png
    - images/cA#m.png
    - images/cE#m.png
    - images/cEb.png
    - images/cAb.png
    - images/logoini.PNG
    - images/A#m.png
    - images/Am.png
    - images/Bm.png
    - images/C#m.png
    - images/Cm.png
    - images/D#m.png
    - images/Dm.png
    - images/Em.png
    - images/F#m.png
    - images/Fm.png
    - images/G#m.png
    - images/Gm.png
    - images/cC#md.png
    - images/cG#md.png
    - images/cA#md.png
    - images/cD#md.png
    - images/cF#md.png
    - images/cFmd.png
    - images/cCmd.png


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
